# Site
name: "HyeGyeong's Blog"
title: "HyeGyeong's Blog"
description: "프로그래밍 공부, 독서, 취미 블로그"
meta_description: ""
baseurl: "/blog"
url: "https://hyegyeong310.github.io"
logo: "assets/images/GitHub-Mark-120px-plus.png.png"
favicon: "assets/images/GitHub-Mark-120px-plus.png"
google_analytics: "UA-126652686-2"
disqus: "hyegyeong310"
include: ["_pages"]
permalink: /:title/
# mailchimp-list: "https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b"

# Authors
authors:
  HyeGyeong:
    name: HyeGyeong
    display_name: HyeGyeong
    gravatar: abadf03e00c5589f7e1929e4e7807c07
    email: hyegyeong310@gmail.com
    web: https://hyegyeong310.github.io/blog/
    git: https://github.com/Hyegyeong310
    twitter: "" # https://twitter.com/wowthemesnet
    description: "프로그래머를 꿈꾸며 JavaScript 공부 중"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-sitemap

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

disqus-shortname: hyegyeong310
