title: HyeGyeong's Blog
email: hyegyeong310@gmail.com
description: 프로그래밍 공부 정리용 블로그입니다.
baseurl: ''
url: ''
twitter_username: ''
github_username: hyegyegon310
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
